- name: Copy file from Ansible Controller to Managed Nodes
  hosts: all

  tasks: 
  - name: Copy ansible.cfg
    copy: 
      src: ansible.cfg
      dest: /tmp/ansible.cfg
      mode: "755"
      owner: kul
      group: users      
