- name: Installing Packages
  hosts: all

  tasks: 
  - name: Installing GIT
    package: 
      name: git
      state: present
  - name: Installing Maven & Java with package list option
    package: 
      name: 
      - java
      - maven
      state: present

- name: Install a package and start the service post same
  hosts: 
  - appservers
  - dbsevers

  tasks: 
  - name: Installing NTP package
    package: 
      name: ntp
      state: present

  - name: Start NTPD Service
    service: 
      name: ntpd
      state: started
      enabled: yes
