- name: Install Terraform
  hosts: all

  tasks: 
  - name: Install UNZIP
    package: 
      name: unzip
      state: present

  - name: download terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip
      dest: /tmp

  - name: Unarchive zip
    unarchive: 
      src: /tmp/terraform_0.13.3_linux_amd64.zip
      dest: /usr/bin
