- name: install vanilla kubernetes
  hosts: all

# vars: 
# -  dockerceversion: docker-ce-19.03.12
# - dockercliversion: docker-ce-cli-19.03.12
# - containerdioversion: containerd.io-1.2.13
  
  roles: 

  - docker
  - install-kubernetes
  - configure-control-plane
