- name: Copy Tomcat Configuration file
  copy:
    src: server.xml
    dest: /opt/{{ tomcatversion }}/conf/server.xml
  notify: 
  - restart-tomcat

- name: Copy Tomcat Init file
  copy:
    src: tomcat-init.sh
    dest: /etc/init.d/tomcat
    mode: "755"
  notify: 
  - restart-tomcat
