  - name: Generate join Command
    shell: kubeadm token create --print-join-command | grep -i kubeadm > /tmp/join-command.sh
    when: inventory_hostname in groups['master']

  - name: Fetching Join Command from k8s master to ansible master
    fetch:
      src: /tmp/join-command.sh
      dest: join-command.sh
      mode: 755
      flat: yes
    when: inventory_hostname in groups['master']
