  - name: create .kube folder
    file:
      path: "{{ ansible_user_dir }}/.kube"
      state: directory
    when: inventory_hostname in groups['master']

  - name: copy conf file or setting up access for centos user to access k8s cluster
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ ansible_user_dir }}/.kube/config"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"
      remote_src: yes
    when: inventory_hostname in groups['master']
