- name: Creating Docker folder
  file: 
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Copying Docker Daemon file to /etc/docker
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0755'
  notify: 
  - restart-docker
